version: "3"

includes:
  build: "./taskfiles/build.yaml"
  deps: "./taskfiles/deps.yaml"
  lint: "./taskfiles/lint.yaml"
  utils: "tools/yscope-dev-utils/taskfiles/utils.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_CPP_SRC_DIR: "{{.ROOT_DIR}}/src"
  G_DEPS_DIR: "{{.G_BUILD_DIR}}/deps"
  G_TEST_BIN_DIR: "{{.G_BUILD_DIR}}/testbin"
  G_TEST_TARGET_SUFFIXES:
    - "all"
    - "container"
    - "error_handling"

tasks:
  clean:
    desc: "Removes the project build directory."
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_BUILD_DIR}}'"

  test-*:
    desc: "Runs unit tests for the specified test target."
    vars:
      TEST_TARGET: >-
        {{printf "unit-test-%s" (index .MATCH 0)}}
    deps:
      - "build:{{.TEST_TARGET}}"
    cmds:
      - "{{.G_TEST_BIN_DIR}}/{{.TEST_TARGET}}"
