version: "3"

includes:
  build: "./taskfiles/build.yaml"
  deps: "./taskfiles/deps.yaml"
  lint: "./taskfiles/lint.yaml"
  test: "./taskfiles/test.yaml"
  utils: "tools/yscope-dev-utils/taskfiles/utils.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_CPP_SRC_DIR: "{{.ROOT_DIR}}/src"
  G_DEPS_DIR: "{{.G_BUILD_DIR}}/deps"

tasks:
  clean:
    desc: "Removes the project build directory."
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_BUILD_DIR}}'"
