version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  deps: "./taskfiles/deps.yaml"
  examples: "./taskfiles/examples.yaml"
  lint: "./taskfiles/lint.yaml"
  test: "./taskfiles/test.yaml"
  ystdlib: "./taskfiles/ystdlib.yaml"

vars:
  # General variables
  # This must match the package name in CMakeLists.txt.
  G_CMAKE_PACKAGE_NAME: "ystdlib"

  # Build directories
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_EXAMPLES_BUILD_DIR: "{{.G_BUILD_DIR}}/examples"
  G_EXAMPLES_DEBUG_BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/debug"
  G_EXAMPLES_RELEASE_BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/release"
  G_YSTDLIB_BUILD_DIR: "{{.G_BUILD_DIR}}/{{.G_CMAKE_PACKAGE_NAME}}"
  G_YSTDLIB_DEBUG_BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/debug"
  G_YSTDLIB_RELEASE_BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/release"

tasks:
  clean:
    desc: "Removes the project build directory."
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_BUILD_DIR}}'"
