version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  deps: "./taskfiles/deps.yaml"
  examples: "./taskfiles/examples.yaml"
  lint: "./taskfiles/lint.yaml"
  test: "./taskfiles/test.yaml"
  utils: "./tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"
  ystdlib: "./taskfiles/ystdlib.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_EXAMPLES_BUILD_DIR: "{{.G_BUILD_DIR}}/examples"
  G_EXAMPLES_SRC_DIR: "{{.ROOT_DIR}}/examples/src"
  G_YSTDLIB_BUILD_DIR: "{{.G_BUILD_DIR}}/ystdlib"
  G_YSTDLIB_SRC_DIR: "{{.ROOT_DIR}}/src"

  G_VALID_BUILD_TYPES:
    - "debug"
    - "release"
  G_VALID_TARGETS:
    - "all"
    - "containers"
    - "error_handling"
    - "wrapped_facade_headers"

tasks:
  clean:
    desc: "Removes the project build directory."
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_BUILD_DIR}}'"
