version: "3"

vars:
  G_CMAKE_CACHE: "{{.G_BUILD_DIR}}/CMakeCache.txt"
  G_CMAKE_CONF_ARGS:
    - "-DCatch2_ROOT={{.G_DEPS_DIR}}/Catch2/Catch2-install"
  G_COMPILE_COMMANDS_DB: "{{.G_BUILD_DIR}}/compile_commands.json"

tasks:
  all:
    desc: "Builds ystdlib-cpp."
    deps:
      - "init"
    cmds:
      - task: ":utils:cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"

  target:
    desc: "Builds specified ystdlib-cpp targets."
    summary: |-
      Builds specified ystdlib-cpp targets.

      Usage: task build:target -- <target0> <target1> ...
    deps:
      - "init"
    cmds:
      - task: ":utils:cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          TARGETS:
            - "{{.CLI_ARGS}}"

  unit-test:
    desc: "Builds ystdlib-cpp unit test targets."
    summary: |-
      Builds specified ystdlib-cpp unit test targets, or run the global unit test target if no
      library is specified.

      Usage: task build -- <lib_name0> <lib_name1> ...
    vars:
      TARGET_NAME: "{{ .CLI_ARGS | default `all` }}"
    cmds:
      - task: "target"
        vars:
          CLI_ARGS: >-
            {{ (printf "unit-test-%s" .TARGET_NAME) }}

  clean:
    desc: "Removes all built artifacts."
    deps:
      - task: ":utils:cmake-clean"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"

  init:
    internal: true
    deps:
      - ":deps:install-all"
    run: "once"
    cmds:
      - task: ":utils:cmake-generate"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          EXTRA_ARGS:
            ref: ".G_CMAKE_CONF_ARGS"
          SOURCE_DIR: "{{.ROOT_DIR}}"
