version: "3"

vars:
  G_CMAKE_CACHE: "{{.G_BUILD_DIR}}/CMakeCache.txt"
  G_CMAKE_CONF_ARGS:
    - "-DCatch2_ROOT={{.G_DEPS_DIR}}/Catch2/Catch2-install"
  G_COMPILE_COMMANDS_DB: "{{.G_BUILD_DIR}}/compile_commands.json"

tasks:
  all:
    desc: "Builds ystdlib-cpp."
    deps:
      - "init"
    cmds:
      - task: ":utils:cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"

  unitTest:
    desc: "Builds ystdlib-cpp's unitTest target."
    deps:
      - "init"
    cmds:
      - task: ":utils:cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          TARGETS: ["unitTest"]

  clean:
    desc: "Removes all built artifacts."
    deps:
      - task: ":utils:cmake-clean"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"

  init:
    internal: true
    deps:
      - ":deps:install-all"
    run: "once"
    cmds:
      - task: ":utils:cmake-generate"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          EXTRA_ARGS:
            ref: ".G_CMAKE_CONF_ARGS"
          SOURCE_DIR: "{{.ROOT_DIR}}"
