version: "3"

tasks:
  target:
    desc: "Builds ystdlib-cpp."
    vars:
      TARGETS:
        ref: "default (list \"all\") .TARGETS"
    deps:
      - ":config-cmake-project"
    cmds:
      - >-
        cmake
        -DCMAKE_C_COMPILER=/usr/bin/gcc-10
        -DCMAKE_CXX_COMPILER=/usr/bin/g++-10
        --build "{{.G_BUILD_DIR}}"
        --parallel {{numCPU}}
        --target {{range .TARGETS}}{{.}} {{end}}

  clean:
    desc: "Removes all built artifacts."
    deps:
      - ":config-cmake-project"
    cmds:
      - >-
        cmake
        --build "{{.G_BUILD_DIR}}"
        --parallel {{numCPU}}
        --target clean
