version: "3"

tasks:
  target:
    desc: "Builds ystdlib-cpp."
    cmds:
      - task: ":utils:cmake-config-and-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          SOURCE_DIR: "{{.ROOT_DIR}}"
          CONF_ARGS: >-
            -DCatch2_ROOT="{{.G_DEPS_DIR}}/Catch2-install"
          JOBS: "{{numCPU}}"

  clean:
    desc: "Removes all built artifacts."
    deps:
      - ":config-cmake-project"
    cmds:
      - >-
        cmake
        --build "{{.G_BUILD_DIR}}"
        --parallel {{numCPU}}
        --target clean

  config-cmake-project:
    internal: true
    sources:
      - "CMakeLists.txt"
      - "{{.TASKFILE}}"
    generates:
      - "{{.G_CMAKE_CACHE}}"
      - "{{.G_COMPILE_COMMANDS_DB}}"
    cmds:
      - "cmake -S '{{.ROOT_DIR}}' -B '{{.G_BUILD_DIR}}'"
