version: "3"

tasks:
  target:
    desc: "Builds ystdlib-cpp."
    cmds:
      - task: ":utils:cmake-config-and-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          SOURCE_DIR: "{{.ROOT_DIR}}"
          CONF_ARGS: >-
            -DCatch2_ROOT="{{.G_DEPS_DIR}}/Catch2-install"
          JOBS: "{{numCPU}}"

  clean:
    desc: "Removes all built artifacts."
    cmds:
      - >-
        cmake
        --build "{{.G_BUILD_DIR}}"
        --parallel {{numCPU}}
        --target clean
