version: "3"

vars:
  G_CMAKE_CONF_ARGS:
    - "-DCatch2_ROOT={{.G_DEPS_DIR}}/Catch2-install"

tasks:
  unittest:
    desc: "Builds and runs ystdlib-cpp's unittest."
    deps:
      - ":deps:install-all"
    cmds:
      - task: ":utils:cmake-generate"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          EXTRA_ARGS:
            ref: ".G_CMAKE_CONF_ARGS"
          SOURCE_DIR: "{{.ROOT_DIR}}"
      - task: ":utils:cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          JOBS: "{{numCPU}}"
          TARGETS:
            - "unitTest"

  clean:
    desc: "Removes all built artifacts."
    deps:
      - task: ":utils:cmake-clean"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
