version: "3"

vars:
  G_CMAKE_CACHE: "{{.G_BUILD_DIR}}/CMakeCache.txt"
  G_CMAKE_CONF_ARGS:
    - "-DCatch2_ROOT={{.G_DEPS_DIR}}/Catch2/Catch2-install"
  G_COMPILE_COMMANDS_DB: "{{.G_BUILD_DIR}}/compile_commands.json"

tasks:
  all:
    desc: "Builds all of ystdlib-cpp."
    deps:
      - "init"
    cmds:
      - task: ":utils:cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"

  target-*:
    desc: "Builds a CMake target."
    vars:
      TARGET: "{{index .MATCH 0}}"
    deps:
      - "init"
    cmds:
      - task: ":utils:cmake-build"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          TARGETS:
            - "{{.TARGET}}"

  unit-test-*:
    desc: "Builds the unit test target for the specified library."
    vars:
      LIBRARY: >-
        {{index .MATCH 0}}
      TEST_TARGET: >-
        {{printf "unit-test-%s" .LIBRARY}}
    preconditions:
      - sh: >-
          {{or (eq .LIBRARY `all`) (has .LIBRARY .G_YSTDLIBS)}}
        msg: |-
          {{.LIBRARY}} is not a valid ystdlib-cpp library!
          List of libraries:
          {{- range .G_YSTDLIBS }}
            {{.}}
          {{- end}}
    cmds:
      - task: "target-{{.TEST_TARGET}}"

  clean:
    desc: "Removes all built artifacts."
    deps:
      - task: ":utils:cmake-clean"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"

  init:
    internal: true
    deps:
      - ":deps:install-all"
    run: "once"
    cmds:
      - task: ":utils:cmake-generate"
        vars:
          BUILD_DIR: "{{.G_BUILD_DIR}}"
          EXTRA_ARGS:
            ref: ".G_CMAKE_CONF_ARGS"
          SOURCE_DIR: "{{.ROOT_DIR}}"
