version: "3"

tasks:
  target:
    desc: "Builds ystdlib-cpp."
    vars:
      TARGETS:
        ref: "default (list \"all\") .TARGETS"
    deps:
      - ":config-cmake-project"
    cmds:
      - >-
        cmake
        --build "{{.G_BUILD_DIR}}"
        --parallel {{numCPU}}
        --target {{range .TARGETS}}{{.}} {{end}}

  unit-test:
    desc: "Builds ystdlib-cpp and run unit tests all libraries."
    deps:
      - ":config-cmake-project"
      - "target"
    cmds:
      - "{{.G_BUILD_DIR}}/unitTest"

  clean:
    desc: "Removes all built artifacts."
    deps:
      - ":config-cmake-project"
    cmds:
      - >-
        cmake
        --build "{{.G_BUILD_DIR}}"
        --parallel {{numCPU}}
        --target clean
